name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload to Hugging Face Space
        uses: huggingface/hub-action@main
        with:
          repo-token: ${{ secrets.HF_TOKEN }}
          space: garygoh/ai-triage-demo
  
